name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupyter-ai
  - langchain-openai
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - nltk
  - spacy
  - spacy-model-en_core_web_sm
  - spacy-model-nl_core_news_lg
  - pip: []
